
server:
  port: 80
  context-path: /Brother

spring:
  datasource:
    url: jdbc:mysql://120.79.95.69:3306/brother_store_server?useUnicode=true&characterEncoding=utf8
    username: username
    password: password
    driver-class-name: com.mysql.jdbc.Driver
    dbcp2:
      initial-size: 10
      max-idle: 10
      min-idle: 5
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

#mybatis
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  config-locations: classpath:mybatis/mybatis-conf.xml
  type-aliases-package: com.brother.entity

logging:
  config: classpath:logback-boot.xml

